---
title: "Getting Started"
author:
- name: David Rach
  affiliation: University of Maryland, Baltimore
  email: drach@som.umaryland.edu
package: Coereba
output:
  BiocStyle::html_document
abstract: |
  How to set up Coereba
vignette: |
  %\VignetteIndexEntry{Getting Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

The Coereba package promises to do these following things...

# Installing Coereba

```{r setup}
# install.packages("devtools")
# devtools::install_github("https://github.com/DavidRach/Coereba")

#install.packages("BiocManager")
#BiocManager::install("Coereba")

library(Coereba)
```

# How To Begin

First off, make sure that you have all the required R packages installed, then
load the libraries. 

```{r, echo=FALSE, results = "hide", warning=FALSE}
suppressPackageStartupMessages({
library(Coereba)
library(flowCore)
library(flowWorkspace)
library(openCyto)
library(data.table)
library(dplyr)
library(ggcyto)
library(purrr)  
})
```

```{r Libraries}
library(Coereba)
library(flowCore)
library(flowWorkspace)
library(openCyto)
library(data.table)
library(dplyr)
library(ggcyto)
library(purrr)
```

To begin, lets access the example .fcs files found with the Coereba package. 

```{r Access Package Data}
FileLocation <- system.file("extdata", package = "Coereba")
fcsFilePattern <- ".fcs$"
myFCSfiles <- list.files(path = FileLocation, pattern = fcsFilePattern, full.names = TRUE, recursive = TRUE)
myFCSfiles
```

```{r sessionInfo, echo = FALSE}
sessionInfo()
```
