# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Coereba_wrappers", use_symbols = TRUE, package_name = "Coereba")

#' @usage NULL
#' @useDynLib Coereba, .registration = TRUE
NULL

#' Verify the matrix type works
#' @export
#' @noRd
describe_matrix <- function(matrix) invisible(.Call(wrap__describe_matrix, matrix))

#' Verify the vector type works
#' @export
#' @noRd
describe_vector <- function(vector) invisible(.Call(wrap__describe_vector, vector))


# nolint end
